### ISSUE TITLE
从本地启动akp文件

### ISSUE THREAD

**Issue by chendx-github** [E-Monkeypox/KISS-Desktop#1]
**Is your feature request related to a problem? Please describe.**
我不希望手机里安装apk
想要从apk文件直接启动程序

**Describe alternatives you've considered, or that are already available within KISS**
从本地启动akp

**Would you be able to contribute code?**
能力不够还不能贡献代码

**Comment by AmySama** [comment]
This feature will be provided next public version, we have uploaded changes about install app via file explorer recently.

**Comment by chendx-github** [comment]
Okay. Looking forward to it.
